### ISSUE TITLE
Ressourcen werden nicht immer korrekt geladen

### ISSUE THREAD

**Issue by Grimaldus12** [hhu-propra2/styleguide#13]
Wenn man versucht, direkt eine konkrete URL aufzurufen (e.g. localhost:8080/fizz/buzz) werden die Ressourcen aus dem Mops package nicht korrekt geladen, da diese dann relativ zur gegebenen URL aufgerufen werden (e.g. localhost:8080/fizz/buzz/img/bla.jpg). Nur wenn man die main-page aufruft, lädt alles korrekt.

Das könnte später zu Problemen bei Links führen.

**Comment by Phlegethon90** [comment]
Danke!
