### ISSUE TITLE
Sidenav und second Nav überlappen

### ISSUE THREAD

**Issue by maste150hhu** [hhu-propra2/styleguide#20]
Wenn man das Browserfenster verkleinert und die secondary Sidenav sich einklappt liegt sie genau in der Sidenav von Mops, wodurch man die sekundäre Navigation nicht vernünftig erreichen kann.

**Comment by Phlegethon90** [comment]
Hmm... Könntest du vielleicht noch Screenshots machen? Oder am besten ein Video...

**Comment by Phlegethon90** [comment]
Und am besten wäre es, wenn du dich an die Bezeichnung laut CSS-Klassen im HTML-Tag hälst.
