### ISSUE TITLE
Bodycontent wird von Anmeldeleiste überlappt

### ISSUE THREAD

**Issue by dobra101** [hhu-propra2/styleguide#23]
Werden bei unserer Abstimmung zu viele Optionen hinzugefügt, dann verschwinden Zurück/Weiter Buttons unseres Formulars hinter der Anmeldeleiste.
<img width="1069" alt="Issue" src="https://user-images.githubusercontent.com/49511094/76293892-2bfe2c80-62b2-11ea-84dd-1f43ddcc20f6.png">

Reproduzierbar unter "Terminfindung erstellen".
Implementierung im UI Branch unter: 
src/main/resources/templates/flows/scheduling/mobileSchedulingChoiceOptions.html
Unser Git: [https://github.com/hhu-propra2/abschlussprojekt-big_f_for_auas](url)

**Comment by Grimaldus12** [comment]
Temporärer Fix: 

` class="d-flex flex-column" style="min-height: 100vh" ` dem `<body>` Tag hinzufügen 
` class="flex-fill" ` dem body-content hinzufügen

**Comment by Phlegethon90** [comment]
`main` wird extra von einem wrapper umgeben, der oben und unten padding hinzufügt, damit das nicht passiert. Zudem ist der footer nicht sticky, sondern fixed. Habt ihr die laut mops.style aktuellste Version vom Styleguide eingebunden? Außerdem: Kann es sein, dass ihr die Buttons aus dem Textfluss rausnehmt (mit float, absolute positionierung oder ähnlichem?)

Ich guck mir mal euer Repo an.

**Comment by Phlegethon90** [comment]
Wie vermutet, werden die Buttons bei euch per `float`-Anweisung aus dem Textfluss rausgenommen (siehe Bild).

<img width="750" alt="Bildschirmfoto 2020-03-10 um 10 58 11" src="https://user-images.githubusercontent.com/44479202/76301767-20653280-62bf-11ea-9d18-080d525b4ed7.png">

`float` ist zwar nicht bad practice, allerdings sollte man für diese Art von Layout die Flexbox nehmen. Bei Bootstrap wird dies durch `row` und `col` erreicht (siehe [Dokumentation](https://getbootstrap.com/docs/4.4/layout/grid/)) oder explizites Setzen von `d-flex` mit anderen Klassen. Vielleicht gibt es aber auch Klassen, die extra für Formulare gedacht sind (siehe [Dokumentation](https://getbootstrap.com/docs/4.4/components/forms/)).

Die Lösung bei euch könnte sein, die Buttons in einem `div` zu kapseln und dann per Flexbox auszurichten.

**Comment by Phlegethon90** [comment]
Ich überlege noch, ob ich dennoch `float`s selbst "fixe". Im Moment spricht dagegen, dass ich dann auch andere Textfluss umgehende CSS-Angaben, wie bspw. `position: absolute` fixen muss, was gar nicht geht. Außerdem sagt der Programmierer ja explizit: "Nimm diese Elemente aus dem Textfluss und dem eigentlichen Layout raus."
