### ISSUE TITLE
Roboto Font wird nicht geladen

### ISSUE THREAD

**Issue by Grimaldus12** [hhu-propra2/styleguide#28]
Beim Laden der Seite wird das `Roboto` Font nicht geladen. Folgende Meldung wird bei mir im Browser-Inspektor angezeigt: 

```
downloadable font: download failed 
(font-family: "Roboto" style:normal weight:700 stretch:100 src index:0):` 
status=2147746065 source: https://mops.style/fonts/roboto/Roboto-Bold.ttf
```

**Comment by Phlegethon90** [comment]
Danke! Das war tatsächlich noch ein Überbleibsel aus einer anderen Version. Ich gucke mal, ob ich es rausnehme oder Roboto hochlade. Die Fallback-Font sollte ja jetzt immer greifen.
