### ISSUE TITLE
Importing mops styleguide in subpaths tries to link css relative to subpaths 

### ISSUE THREAD

**Issue by LanPodder** [hhu-propra2/styleguide#29]
Creating a controller in spring boot, that has a default path other than root.
When adding template code, it adds css relative to sub path.
For instance using "localhost:8080/my/path/to/getmapping" with
```
@Controller
@RequestMapping("/my/path/to")
class [...]
    @GetMapping("/getmapping")
    [...]
```
looks like this:
![Screenshot from 2020-03-13 09-16-02](https://user-images.githubusercontent.com/35526460/76602478-48e16c80-650b-11ea-81ac-fedd30d411bb.png)

And when looking at this pages source code:
![Screenshot from 2020-03-13 09-16-38](https://user-images.githubusercontent.com/35526460/76602581-8219dc80-650b-11ea-84e5-403d1bca3bc3.png)

We can see it is trying to import/link css. But when trying to open those css links, we are redirected to `localhost:8080/my/path/to/css/file.css`

However those css files lie on `localhost:8080/css/file.css`

**Comment by LanPodder** [comment]
To fix this, there needs to be a leading slash in links:

![Screenshot from 2020-03-13 09-23-45](https://user-images.githubusercontent.com/35526460/76602995-66630600-650c-11ea-9ff1-dd1254694b63.png)

**Comment by n2o** [comment]
Verwendest du die neueste Version vom Stylesheet?

**Comment by n2o** [comment]
2.2.0

**Comment by n2o** [comment]
Das haben wir vor ner Woche repariert: https://github.com/hhu-propra2/styleguide/blob/development/src/main/resources/templates/mopslayout.html#L7-L9

**Comment by LanPodder** [comment]
Used 2.0.0.
using 2.2.0 works fine.
