### ISSUE TITLE
jquery fehlt

### ISSUE THREAD

**Issue by TimurKelman** [hhu-propra2/styleguide#30]
Der Anleitung zu bootstrap [collapsible](https://www.w3schools.com/bootstrap/bootstrap_collapse.asp) nach braucht man 2 Skripte: `bootstrap.min.js` und `jquery.min.js`. Der erste ist [bereits da](https://github.com/hhu-propra2/styleguide/blob/901a0466f6d29498bbaa34ac308bccd01855ceaf/gulpfile.js#L18).

Auf [getbootstrap.com](https://getbootstrap.com/) sind folgende Scripte angegeben.

```html
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
```

 Es wäre toll wenn wir zumindest `jquery.js` dabei hätten, am besten natürlich alle 3.

**Comment by Phlegethon90** [comment]
da bootstrap sozusagen pflicht ist, haben wir die css direkt eingebettet und die dazugehörige js bereitgestellt. letztere kann einfach referenziert werden, falls diese benötigt wird. alles weitere könnt ihr selbst per headcontent (siehe https://mops.style/#fragments) hinzufügen. dies kann in eurem eigenen static ordner liegen.

**Comment by TimurKelman** [comment]
es ist kein Problem die .js direkt zu referenzieren, ich fand es nur merkwürdig, dass nur eins der 3 Skripte im Style dabei waren.

**Comment by n2o** [comment]
Alles gut, danke für den Hinweis :-) Wir brauchen nur nicht alles daraus und müssen das auch nicht immer und auf jeder Unterseite mitliefern.

**Comment by Phlegethon90** [comment]
die antwort ist simpel: diese sind für die core-funktionalitäten von bootstrap (und somit für die meisten seiten) nicht erforderlich.

**Comment by TimurKelman** [comment]
...aber die `bootstrap.min.js` ist auch nicht automatisch eingebettet (glaube ich). Sie ist nur "in der Nähe" und kann mit `<script src="/js/bootstrap.min.js"></script>` dazugeholt werden.

Momentan sieht es also wie folgt.
```js
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="/js/bootstrap.min.js"></script>
```

Ich fänd folgende Variante schöner.
```js
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
```

**Comment by Phlegethon90** [comment]
korrekt, weil die js nicht für alles erforderlich ist. vereinfacht ausgedrückt: je weniger eine sache erforderlich ist, desto weiter liegt sie von euch entfernt.

letztere variante ist doch, wie oben erwähnt, möglich, indem ihr die entsprechenden dateien selbst in `static/js` kopiert und dann im headcontent übergibt.

**Comment by TimurKelman** [comment]
> letztere variante ist doch, wie oben erwähnt, möglich, indem ihr die entsprechenden dateien selbst in `static/js` kopiert und dann im headcontent übergibt.

ja, werden wir wohl tun.
