### ISSUE TITLE
Zurück zur Application on save Account Data

### ISSUE THREAD

**Issue by otlin100** [hhu-propra2/styleguide#32]
Wenn man links unten auf seinen Account klickt, kommt ja eine Ansicht über die Accountdaten. Wenn man diese bearbeitet und speichert, kommt man nicht mehr zurück in die Application. Im Moment muss man manuell die URL eintippen.
Kann das in Zukunft dahingehend geändert werden, dass man beim Speichern oder Abbrechen zurückkommt?

**Comment by Phlegethon90** [comment]
@RutenkolkC da du ja auch an der keycloak-demo gearbeitet hast, könntest du dich darum kümmern? sollte anfangs nur account verlinken.

**Comment by n2o** [comment]
Da ist nicht viel zu machen, liegt in der Natur des Layouts. Da es hart im Mopslayout verdrahtet ist, kann man keine redirect_uri setzen.

Die redirect_uri wird sonst automatisch gesetzt wenn man auf eine Route klickt die geschützt ist.

**Comment by Phlegethon90** [comment]
dann könnte man doch einfach den wert von "href" abändern zu bspw. "/login", welches geschützt ist. man wird also weitergeleitet auf keycloak und loggt sich ein... keycloak redirectet an "/login". im controller prüft man dann, ob "account" gesetzt ist und redirectet weiter (bspw. zu "/").

**Comment by Phlegethon90** [comment]
kann nicht schlafen und hab es mal umgesetzt.
