### ISSUE TITLE
Navbar Elemente hängen zu nah am Bildschirmrand

### ISSUE THREAD

**Issue by RutenkolkC** [hhu-propra2/styleguide#4]
Unter Manchen Systemen werden die Elemente der Navbar so weit links angeordnet, dass der Text / die Icons abgeschnitten werden.

Dieses Verhalten tritt sowohl unter Chromium, als auch Firefox auf. 
Beobachtet auf Systemen mit Kubuntu 18.04

![Screenshot_20200303_140855](https://user-images.githubusercontent.com/27628243/75778678-8d754700-5d58-11ea-8b81-20b693a4f6d5.png)

![Screenshot_20200303_135613](https://user-images.githubusercontent.com/27628243/75777758-d3311000-5d56-11ea-9606-219663d6ef8b.png)

**Comment by Phlegethon90** [comment]
auf den ersten blick würd ich sagen, dass die scrollbar die breite klaut... "scroll-padding" könnte die lösung sein... hmm...

**Comment by n2o** [comment]
Das tritt interessanterweise auch aufs Jens' Macbook auf. Bei mir allerdings nicht. Jens hat das Verhalten im Safari, Firefox, Chrome auch gehabt

**Comment by RutenkolkC** [comment]
Habe das Problem mittlerweile auch unter Windows beobachtet. Scheint also auf diversen OS aufzutreten.

**Comment by n2o** [comment]
Spannend, ich verstehe nur nicht wieso :D

**Comment by Phlegethon90** [comment]
weil manche browser einer scrollbar eine explizite breite im box-sizing zuweisen. der internet explorer haut zum beispiel 2 scrollbars dran, obwohl es bei der einen nichts zu scrollen gibt.

**Comment by RutenkolkC** [comment]
Aber auch mit Scrollbar sollte das korrekt am Rand gelayoutet werden, wenn es z.B. eine entsprechend lange Liste an Elementen gibt.

**Comment by Phlegethon90** [comment]
> Aber auch mit Scrollbar sollte das korrekt am Rand gelayoutet werden, wenn es z.B. eine entsprechend lange Liste an Elementen gibt.

keiner hat das gegenteil behauptet... außerdem wird es ja in anderen browsern mit scrollbar korrekt dargestellt... es geht darum, dass anscheinend viele browser die scrollbar unterschiedlich in das box-modell packen (passiert übrigens auch in reinem bootstrap).

ich kümmer mich drum.

**Comment by Phlegethon90** [comment]
ist im pr behoben. hing tatsächlich mit der scrollbar und dem padding zusammen.
