### ISSUE TITLE
Authentifizierung korrekt umsetzen

### ISSUE THREAD

**Issue by n2o** [hhu-propra2/styleguide#6]
Aktuell wird Keycloak nicht korrekt verwendet, man sieht beispielsweise unten im login nicht wenn man angemeldet ist. Einfach an der Keycloak Demo langhangeln.

**Comment by Phlegethon90** [comment]
das wird nicht nicht korrekt verwendet - es wird gar nicht verwendet.
es war doch gar nicht gedacht, dass der styleguide dies benutzt.
im gegenteil: als ich dies vorgeschlagen habe, habt ihr explizit mit einem lächeln gesagt, dass der living styleguide kein subsystem ist.
warum sollte etwas, was kein subsystem ist, eine authentifizierung nutzen, die seitenübergreifend (also doch zwischen systemen) ist?

also jetzt doch? ich frag nur... nicht, dass es dann ein weiteres hin und her gibt.

**Comment by n2o** [comment]
Können wir ja diskutieren. Mein Gedanke ist: Der Styleguide stellt den Button zur Verfügung und verlinkt ihn, also sollte da auch was hinter sein 🤔  das in die Keycloak-Demo schieben kann ich auch nachvollziehen, sonst wäre das ja redundant.

**Comment by Phlegethon90** [comment]
ich bin noch immer dafür, dass der styleguide ein subsystem ist, da er ja teil eines großen ganzen (mops) ist und für die entwicklung neuer systeme und das dasein bestehender systeme herangezogen wird. damit ist es auch logisch, dass er keycloak benutzt. um die verwendung von spring security zu zeigen, könnte man beim styleguide einen endpunkt einschränken, der nur für angemeldete nutzer ist. dann könnte man sogar die keycloak demo löschen. und alles wäre schön schlank.
