### ISSUE TITLE
Bilder optimieren / verkleinern

### ISSUE THREAD

**Issue by n2o** [hhu-propra2/styleguide#9]
Die Bilder der Hunde sind viel zu groß. elvis_young.jpg ist beispielsweise 392 KB groß und wird responsiv genutzt.

Mampfi ist 95,3 KB und 583x729 Pixel groß, es werden aber nur 38x38 Pixel genutzt in der Seitenleiste.

Es gibt bestimmt ein Thymeleaf Plugin welches die Bilder automatisch auf die richtige Größe resized. Aus Django kenne ich beispielsweise [easy_thumbnails](https://github.com/SmileyChris/easy-thumbnails). Das Markup sieht dann so aus:

```python
<img src="{% thumbnail profile.photo 50x50 crop %}" alt="" />
```

oder per Alias für alle Seitenleistenelemente auf einmal definiert: https://github.com/SmileyChris/easy-thumbnails#using-a-predefined-alias

**Comment by n2o** [comment]
In Google's Lighthouse schneiden wir schonmal gut ab 😌 

![image](https://user-images.githubusercontent.com/1507474/75858016-9bc67000-5df7-11ea-8083-5b5692e3d388.png)

Hauptkritik sind die Bilder:

![image](https://user-images.githubusercontent.com/1507474/75858039-a7b23200-5df7-11ea-9c54-fc5888a9808f.png)

Lighthouse gibt es in jedem Chromium-basierten Browser in der Entwicklerkonsole unter dem Tab "Audits"

**Comment by Grimaldus12** [comment]
Ich würde da mal ein bisschen dran rumprobieren

**Comment by Grimaldus12** [comment]
PR: #18
